table social_media_ad_optimization
	lineageTag: bcab1b58-30f5-4bed-b293-fd0f24c6a081

	column user_id
		dataType: string
		lineageTag: 877d5648-e4fb-4a07-a1d4-33a7dd0d9dbc
		summarizeBy: none
		sourceColumn: user_id

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 61147094-d61a-4680-b321-f51cc9a761fa
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

	column gender
		dataType: string
		lineageTag: 5164c58d-f4c5-427c-bf1a-ea20e507a473
		summarizeBy: none
		sourceColumn: gender

		annotation SummarizationSetBy = Automatic

	column location
		dataType: string
		lineageTag: 3bcfea82-e9c5-42a0-b8bf-54f9ab50ab2c
		summarizeBy: none
		sourceColumn: location

		annotation SummarizationSetBy = Automatic

	column interests
		dataType: string
		lineageTag: 1b173290-e916-4091-b151-57cdefafc75d
		summarizeBy: none
		sourceColumn: interests

		annotation SummarizationSetBy = Automatic

	column ad_id
		dataType: string
		lineageTag: e1a13db5-fee2-4460-af22-ea6532492c88
		summarizeBy: none
		sourceColumn: ad_id

		annotation SummarizationSetBy = Automatic

	column ad_category
		dataType: string
		lineageTag: e5b157f3-ac6e-4117-9f50-55a4a3102b37
		summarizeBy: none
		sourceColumn: ad_category

		annotation SummarizationSetBy = Automatic

	column ad_platform
		dataType: string
		lineageTag: 5b13538b-343a-4d85-a23e-3e688bfac4ca
		summarizeBy: none
		sourceColumn: ad_platform

		annotation SummarizationSetBy = Automatic

	column ad_type
		dataType: string
		lineageTag: 29810de1-c203-4754-acce-5efc75c7f9ed
		summarizeBy: none
		sourceColumn: ad_type

		annotation SummarizationSetBy = Automatic

	column impressions
		dataType: int64
		formatString: 0
		lineageTag: 8abe1397-aac3-465a-b13a-e38487cceb7b
		summarizeBy: sum
		sourceColumn: impressions

		annotation SummarizationSetBy = Automatic

	column clicks
		dataType: int64
		formatString: 0
		lineageTag: a9b9144a-d45b-45e0-af73-6a43a9011647
		summarizeBy: sum
		sourceColumn: clicks

		annotation SummarizationSetBy = Automatic

	column conversion
		dataType: string
		lineageTag: f202bf3e-b83a-4cb8-876b-0e5abe833933
		summarizeBy: none
		sourceColumn: conversion

		annotation SummarizationSetBy = Automatic

	column time_spent_on_ad
		dataType: double
		lineageTag: 69fa21b0-bd7d-40ec-af89-cea61aa468e1
		summarizeBy: sum
		sourceColumn: time_spent_on_ad

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column day_of_week
		dataType: string
		lineageTag: ccbccc49-527f-4819-ade3-cfefdc52411b
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column device_type
		dataType: string
		lineageTag: 4f08af75-0f22-4e76-b060-5ed8624d43ed
		summarizeBy: none
		sourceColumn: device_type

		annotation SummarizationSetBy = Automatic

	column engagement_score
		dataType: double
		lineageTag: 2c5ebb0e-d71c-4a5f-8517-d7da11cd4c06
		summarizeBy: sum
		sourceColumn: engagement_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition social_media_ad_optimization = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mark6\OneDrive\Desctop\social_media_ad_optimization.csv"),[Delimiter=",", Columns=16, Encoding=1251, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Promoted Headers", {{"engagement_score", type number}}, "en-US"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"age", Int64.Type}, {"impressions", Int64.Type}, {"clicks", Int64.Type}}),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type", {{"time_spent_on_ad", type number}}, "en-US")
				in
				    #"Changed Type with Locale1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

